name: 'imagenie'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.3.1
  - ipykernel=6.29.5
  - altair-all=5.4.*
  - vega_datasets=0.9.0
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - scipy=1.14.1
  - matplotlib>=3.2.2
  - scikit-learn=1.5.2
  - poetry=1.4.0
  - cookiecutter=2.5.0
  